config/routes.rb
Blog::Application.routes.draw do
  resources :users, only: [:update]

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "/:id", to: "users#show", as: "user_slug"
  get "/:id/edit", to: "users#edit", as: "user_edit"
  
  get "/:user_id/new", to: "posts#new", as: "user_new_post"
  get "/:user_id/:post_id/edit", to: "posts#edit", as: "user_edit_post" 
  get "/:user_id/:post_id", to: "posts#show", as: "user_post"
  put "/:user_id/:post_id", to: "posts#update"
  delete "/:user_id/:post_id", to: "posts#destroy"
  
  resources :user do
    resources :posts
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :post_id, :text
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  belongs_to :user
  has_many :comments

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # why get rid of?
  # attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  attr_accessible :blog_title

  extend FriendlyId
  friendly_id :blog_title, use: :slugged

  has_many :user_blogs
  has_many :posts
  
  validates :blog_title, :uniqueness => true
  # validates_format_of :login, :with => /\A[a-z0-9]+\z/i

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)

  end
end

  # Notes
  # self.from_omniauth(auth)
  # - first_or_initialize is new method 
  #     return user record matching :provider and :uid
  #     or, initialize a new user record
  # - tap passes the user instance to the block
  # - next, set attributes provided by the hash
  # - notice we're calling methods on auth
  #     this is because oauth uses hashy gem to call methods as keys
  #     to access hash values

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.save

    redirect_to @post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to @comment.post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :ensure_user_is_logged_in, except: [:show, :index]
  before_filter :no_root_path_logged_in, only: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # @post = Post.find(params[:id])
    user = User.find(params[:user_id])
    @post = Post.find(params[:post_id], :conditions => { :user_id => user })

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    unless current_user.slug == params[:user_id]
      return redirect_to user_slug_path(current_user), notice: "I don't think so"
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    user = User.find(params[:user_id])
    @post = Post.find(params[:post_id], :conditions => { :user_id => user })

    unless current_user == @post.user
      return redirect_to user_slug_path(current_user), notice: "I don't think so"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_slug_path(current_user), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    user = User.find(params[:user_id])
    @post = Post.find(params[:post_id], :conditions => { :user_id => user })

    unless current_user == @post.user
      return redirect_to root_path, notice: "I don't think so"
    end

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to user_slug_path(current_user), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    user = User.find(params[:user_id])
    @post = Post.find(params[:post_id], :conditions => { :user_id => user })

    unless current_user == @post.user
      return redirect_to user_slug_path(current_user) , notice: "I don't think so"
    end

    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_slug_path(current_user), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def ensure_user_is_logged_in
    redirect_to root_path, :notice => "You must be logged in" unless current_user
  end

  def no_root_path_logged_in
    if current_user
      redirect_to user_slug_path(current_user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    user.save
    session[:user_id] = user.id

    if user.blog_title?
      # redirect_to "/#{user.slug}"
      redirect_to user_slug_path(user)
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to user_slug_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      # else
      #   format.html { render action: "edit" }
      #   format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  include FacebookShare

  def facebook_share_description_text
    if @post
      truncate( remove_white_space("#{@post.title} - #{@post.text}"), :length => 320)
    elsif @user
      @user.blog_title
    else
      "Tagline"
    end
  end

  def remove_white_space(string)
    string.gsub("\n", " ").squeeze(" ").strip
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag :atom, "/posts.atom" %>
</head>
<body>
<div id="navigation">
  <div style="float:left;">
  <% if current_user %>
    <%= link_to 'Luddite Blogger', user_slug_path(current_user)  %>
  <% else %>
    <%= link_to 'Luddite Blogger' %>
  <% end %>
  </div>
  <div style="float:right;">
    <%= link_to 'Share on Facebook', '#', :class => "fb_share"  %>
    <%= facebook_share_once(
          :name => "Luddite Blogger", 
          :picture => "http://etc.usf.edu/clipart/62800/62839/62839_typewriter_lg.gif",
          :description => escape_javascript(facebook_share_description_text) ) %>
    <% if current_user %>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in", "/auth/facebook", id: "sign_in" %>
      <% end %>
  </div>

</div>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  
    <%= yield %>

  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for([current_user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# f.hidden_field :user_id, current_user %>

  <div class="field">
    <%= f.text_field :title, placeholder: "<Title>" %>
  </div>
  <div class="field">
    <%= f.text_area :text, placeholder: "<Text>" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Post", :class => "submit" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_slug_path(current_user) %>

app/views/posts/index.html.erb
<div id="home">
  <h1>Luddite Blogger</h1>
  <img src="http://etc.usf.edu/clipart/62800/62839/62839_typewriter_lg.gif" style="height:300px; width:300px">
  <h3 style="font-style:italic">No images. No links. Just old-fashioned text.</h3>

  <% if current_user && !current_user.blog_title? %>
   <p>To get started choose a name for your blog.</p>
   <p>(Note: You won't be able to change the title, so choose carefully...)</p>
   <%= render 'users/form' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= simple_format(@post.text) %>

<!-- <h2>Comments</h2> -->


  <p id="links">
  <% if current_user == @post.user %>
    <%= link_to "Back", user_slug_path(current_user) %>
    |
    <%= link_to "Edit", user_edit_post_path(current_user, @post) %>
    |
    <%= link_to "Delete", user_post_path, :method => :delete, 
                                          :confirm => "Are you sure?" %>

  <% end %>
  </p>

app/views/users/_form.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this User's blog title from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blog_title %><br />
    <%= f.text_field :blog_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
Want to change your blog title?
<%= render 'form' %>

app/views/users/show.html.erb
<div id="home">

  <% if current_user && (current_user = @user) %>
    <h1><%= link_to(@user.blog_title, user_edit_path) %></h1>
  <% else %>
    <h1><%= @user.blog_title %></h1>
  <% end %>
  

  <% if current_user && !current_user.blog_title? %>
   <p>To get started choose a name for your blog.</p>
   <p>(Note: You won't be able to change the title, so choose carefully...)</p>
   <%= render 'users/form' %>

  <% end %>

  <% if current_user && current_user.blog_title? && (current_user == @user) %>
    <h2>
      <%= link_to "+ Add New Post +", user_new_post_path(current_user) %>
    </h2>
  <% end %>

  <% unless @posts.blank? %>
    <% @posts.each do |post| %>

      <h2><%= link_to post.title, user_post_path(post.user, post) %></h2>
      <!-- <p> -->
        <% time_ago_in_words post.created_at %> 
      <!-- </p> -->
      <!-- <p> -->
        <% truncate post.text %>
      <!-- </p> -->
    <% end %>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>